# Generated by Django 3.0.8 on 2021-01-25 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date_added',
            field=models.DateField(default=datetime.date.today, verbose_name='Date added'),
        ),
    ]
